<?php
    /** @var \JaroslawZielinski\OTPComponent\Block\Container\Form\SubmitScript $block */
    $formId = $block->getFormId();
    $recaptchaBlock = $block->getRecaptchaBlock();
    /** @var \JaroslawZielinski\OTPComponent\Block\Container\Form $parentBlock */
    $parentBlock = $block->getParentBlock();
    /** @var \JaroslawZielinski\OTPComponent\Block\Container\Form\ReCaptcha $recaptchaHtmlBlock */
    $recaptchaHtmlBlock = $parentBlock->getChildBlock($recaptchaBlock);
    $submitUrl = $parentBlock->getSubmitUrl();
    $statusOK = \JaroslawZielinski\OTPComponent\Controller\Form\Otp::STATUS_OK;
?>
<script type="text/javascript">
    require([
        'jquery',
        'mage/translate',
        'underscore',
        'otpForms',
        'otpFormsUtils',
        'prototype',
        'mage/validation'
    ], function ($, $t, _, otpForms, otpFormsUtils) {
        $(document).ready(function() {
            $('#<?= $formId; ?>').on('submit', function (event) {
                event.preventDefault();
                event.stopPropagation();
                const form = document.forms.namedItem('<?= $formId; ?>');
                $(form).validation();
                // Initialize button state
                let isValid = $(form).validation('isValid');
                if (isValid) {
                    otpForms.showLoader('<?= $formId; ?>');
                    const oData = new FormData(form);
                    const oReq = new XMLHttpRequest();
                    oReq.open('POST', '<?= $submitUrl; ?>', true);
                    oReq.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
                    oReq.onload = function(oEvent) {
                        const STATUS_OK = '<?= $statusOK; ?>';
                        var response = JSON.parse(oReq.response);
                        var messageText = response.message;
                        var resultText = response.results;
                        var status = response.status;
                        if (STATUS_OK === status && 200 === oReq.status) {
                            $('#parent-<?= $formId; ?>').html(resultText);
                            otpFormsUtils.ajaxMagentoReinit('#parent-<?= $formId; ?>');
                        }
                        const messageTemplate = STATUS_OK === status
                            ? '<div class="alert alert-success" role="alert"><%= message %></div>'
                            : '<div class="alert alert-danger" role="alert"><%= message %></div>';
                        const myMessage = _.template(messageTemplate)({message: messageText});
                        $('#message-<?= $formId; ?>').hide();
                        $('#message-<?= $formId; ?>').html(myMessage);
                        otpForms.hideLoader('<?= $formId; ?>');
                        $('#message-<?= $formId; ?>').show();
                        if (!(STATUS_OK === status && 200 === oReq.status)) {
                            otpForms.hideLoader('<?= $formId; ?>');
                            <?php if (!empty($recaptchaHtmlBlock)): ?>
                            <?= $recaptchaHtmlBlock->jsFailedReset($formId); ?>
                            <?php endif; ?>
                        }
                    };
                    oReq.send(oData);
                } else {
                    <?php if (!empty($recaptchaHtmlBlock)): ?>
                    <?= $recaptchaHtmlBlock->jsFailedReset($formId); ?>
                    <?php endif; ?>
                }
            });
        });
    });
</script>
